services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: mobile_app_backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: mobile_app_frontend
    ports:
      - "8000:80" 
    volumes:
      - ./frontend:/app/src 
      - ./backend:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mobile_app_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mobile_app_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mobile_app_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local