pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials'
    }

    stages {
        stage('1. Initialize') {
            steps {
                script {
                    echo "Mulai build..."
                    cleanWs()
                    checkout scm
                }
            }
        }
        
        stage('2. Build Docker Images') {
            steps {
                dir('project_mobile_app') {
                    script {
                        echo "Membangun image dari docker-compose.yaml..."
                        sh 'docker compose build --parallel'
                    }
                }
            }
        }

        stage('3. Push to Docker Hub') {
            steps {
                dir('project_mobile_app') {
                    script {
                        echo "Logging in and pushing images..."
                        docker.withRegistry("https://index.docker.io/v1/", DOCKER_CREDENTIALS_ID) {
                            sh 'docker compose push'
                        }
                    }
                }
            }
        }
        
        stage('4. Cleanup') {
            steps {
                script {
                    echo "Membersihkan image Docker yang tidak terpakai..."
                    sh 'docker image prune -f'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Build pipeline selesai.'
        }
    }
}